### ISSUE TITLE
GridView "Select" command and SelectedIndexChanged stops the circuit 

### ISSUE THREAD

**Issue by MG1376** [Jurioli/Blazor.WebForm.Components#17]
GridView select command and selectedindexchanged event stops page circuit. after executing the event handler, the gridview and the page are disabled:

`OnSelectedIndexChanged="Selected_Changed"`

```
 <ItemTemplate TItem="GreenPaperItem">     
     <asp.LinkButton Text="Select" CommandName="Select">

     </asp.LinkButton>
     <asp.Button Text="Delete" CommandName="Delete" CssClass="btn btn-danger">

     </asp.Button>
     <asp.Button Text="Edit" CommandName="Edit" CssClass="btn btn-primary">

     </asp.Button>
 </ItemTemplate>
```

```
 int selectedValue = -1;
 protected void Selected_Changed(object sender, EventArgs e)
 {
     gvSelectedValue = Convert.ToInt32(gv.SelectedValue);
     StateHasChanged();
 }
```
When I hover the mouse on Edit and Delete buttons nothing appears but when I hover on Select Button a "_doPostback.." appears under the page. probably this feature is not implemented yet. 
the problem can be easily solved by passing context.Id to event handler and attach event handler to the button, but then it is not the asp.net way.

**Comment by Jurioli** [comment]
You need DataBind in SelectedIndexChanged because the original [HandleSelect](https://referencesource.microsoft.com/System.Web/UI/WebControls/GridView.cs.html#2ccc566cdba50b6c) did not add RequiresDataBinding = true.

```
 protected void Selected_Changed(object sender, EventArgs e)
 {
     gvSelectedValue = Convert.ToInt32(gv.SelectedValue);
     gv.DataBind();
 }
```
