### ISSUE TITLE
Disable element body

### ISSUE THREAD

**Issue by chiendang1709** [Jurioli/Blazor.WebForm.Components#19]
Thank you, but i have 1 issure
When i use asp.TextBox then table disable lose body and lose cssclass
![Screenshot 2024-09-17 122417](https://github.com/user-attachments/assets/2aec9823-f910-48b5-8cf3-b17e52860e4e)
Do you know reason?

**Comment by Jurioli** [comment]
How to reproduce? which rendering mode?

**Comment by chiendang1709** [comment]
if i use <asp.TextBox @bind-Text="context.Date"></asp.TextBox> or any asp. in ItemTemplate , EditItemTemplate  then when render show los element tbody, when use  <asp.BoundField HeaderText="Date" DataField="Date" DataFormatString="{0:yyyy/M/d}"></asp.BoundField> then when render has element then not lose (server-side rendering)
![image](https://github.com/user-attachments/assets/92ee3869-1b87-4b25-b9c8-5d757e1a5ddf)

Do you have document?

**Comment by Jurioli** [comment]
If your Date property is not a String, you need to handle the conversion.
(adding additional string property, etc...)
