### ISSUE TITLE
Issues getting my first BlazorWebApp project working with this package. 

### ISSUE THREAD

**Issue by theKingdomAge** [Jurioli/Blazor.WebForm.Components#20]
I started typing up a long description of how I added the nuget packages to a new BlazorWebApp and trying to get it build without errors. But it got too long. 

Can you please make a sample app that uses a few or all of the Components and add it to the repository please?

When I copy the code samples from https://blazorwebformdemo.github.io/ pages into my project it doesn't work.

Thank You.

**Comment by Jurioli** [comment]
You can obtain Visual Studio project templates from https://marketplace.visualstudio.com/items?itemName=Jurio-Li.BlazorWebFormTemplate .

**Comment by theKingdomAge** [comment]
I got it working... https://github.com/theKingdomAge/Blazor.WebForm.Components.Sample
