### ISSUE TITLE
About the demo

### ISSUE THREAD

**Issue by agriffard** [Jurioli/Blazor.WebForm.Components#6]
Can you please explain how you publish the demo on https://github.com/BlazorWebFormDemo/BlazorWebFormDemo.github.io ?

**Comment by Jurioli** [comment]
Sorry, I'm not following you.
The demo just publish static site on github pages.

**Comment by agriffard** [comment]
Ok, but can we find the source code somewhere?

**Comment by Jurioli** [comment]
Not public yet, but example code at razor tab is same.

**Comment by agriffard** [comment]
Ok, thank you.
