### ISSUE TITLE
asp.GridView / asp.BoundField

### ISSUE THREAD

**Issue by Campos85** [Jurioli/Blazor.WebForm.Components#9]
I have these properties in my code and I didn't find the correlation using GridView component

itens
 ItemStyle-Wrap
 ItemStyle-ForeColor
 ItemStyle-HorizontalAlign
 HeaderStyle-Wrap
 ItemStyle-CssClass
 HeaderStyle-CssClass

sample
<asp.BoundField DataField="code1" HeaderText="code1" ItemStyle-Wrap="false" />
<asp.BoundField DataField="code2" HeaderText="code2"  SortExpression="code" ItemStyle-ForeColor="blue" />
<asp.BoundField DataField="code3" HeaderText="code3"  ItemStyle-HorizontalAlign="Right" HeaderStyle-Wrap="false" />
 <asp.BoundField DataField="code4" HeaderText="" ItemStyle-CssClass="hiddencol" HeaderStyle-CssClass="hiddencol" SortExpression="value" />

**Comment by Jurioli** [comment]
Those properties with a minus sign are not implemented, you can use the equal inner properties. ex:
```
            <asp.BoundField HeaderText="Code1" DataField="Code1">
                <ItemStyle Wrap="false" ForeColor="blue" />
            </asp.BoundField>
```

**Comment by Campos85** [comment]
Perfect !!

Thanks
